<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<InternalsVisibleTo>TrelloClone.Tests</InternalsVisibleTo>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Areas\Chat\Data\**" />
	  <Compile Remove="Areas\Chat\Models\**" />
	  <Compile Remove="Areas\Chat\Views\**" />
	  <Content Remove="Areas\Chat\Data\**" />
	  <Content Remove="Areas\Chat\Models\**" />
	  <Content Remove="Areas\Chat\Views\**" />
	  <EmbeddedResource Remove="Areas\Chat\Data\**" />
	  <EmbeddedResource Remove="Areas\Chat\Models\**" />
	  <EmbeddedResource Remove="Areas\Chat\Views\**" />
	  <None Remove="Areas\Chat\Data\**" />
	  <None Remove="Areas\Chat\Models\**" />
	  <None Remove="Areas\Chat\Views\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.9" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
		<PackageReference Include="Scalar.AspNetCore" Version="2.16.9" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Areas\Admin\Controllers\" />
		<Folder Include="Areas\Customer\Controllers\" />
		<Folder Include="DTOs\" />
		<Folder Include="Repository\IRepository\" />
		<Folder Include="Services\IServices\" />
	</ItemGroup>

</Project>